### PR TITLE
Disabling hpd check for MA mcts sync

### PR DESCRIPTION
**Pull request by koshalt**

### CODE REVIEW

**Comment by koshalt** [comment]
ok to test

**Comment by frankhuster** [comment]
Why about having HPD checking enabled or disabled based on a setting instead of just ripping out the code?

**Comment by koshalt** [comment]
@frankhuster That's exactly what the ripped out code used to do...and it still does for kilkari. Turns out that flw sync was never meant to be part of the hpd check and that was lost in communication.

**Comment by frankhuster** [comment]
Okeydokey, then LGTM

**Pull request merged**
